### ISSUE TITLE
New registered user can not use service

### ISSUE THREAD

**Issue by lapd-viosoft** [globocom/gsh#48]
Hi,
I did follow the guide but when trying to connect to the host, I got this message
```sh
{"details":"Your roles are: []","message":"You don't have permission to request this certificate","result":"fail"}
```
I think there are missed step to grant/add roles for the new user.
Can you please tell me how to add a role to a new user?
Thank!

**Comment by mdjunior** [comment]
Hi,

You need add roles (https://github.com/globocom/gsh/wiki/cli-commands#add-a-new-role). After creation of roles, you need assign them to an user using (https://github.com/globocom/gsh/wiki/cli-commands#assign-a-role-to-an-user).

Example (1010.0.0/24 -> 10.10.10.0/24):
```
gsh role-add example -s 10.10.0.0/24 -d 10.10.10.0/24 -u '*' -a permit-pty
gsh role-assign example alice@example.com
```

**Comment by lapd-viosoft** [comment]
Thank you very much!
